### ISSUE TITLE
Center UI elements

### ISSUE THREAD

**Issue by agneevX** [N-l1/lovelace-soft-ui#12]
How do I center UI elements?

<img width="517" alt="image" src="https://user-images.githubusercontent.com/19761269/84435048-b7d77a00-ac4e-11ea-859b-14a0a347ad8d.png">

**Comment by KTibow** [comment]
You can adjust the
```yaml
    style: |
      ha-card {
```
and add more/less `padding`/`margin`. You can also make them bigger too. If you resize your window, it might look better...

**Comment by N-l1** [comment]
Hi, @agneevX please also check issue #7

**Comment by Harry-1976** [comment]
Or you can create a blank button on each side using 

Colortype: blank-card

The blank buttons on each side will center your 4 buttons.

**Comment by agneevX** [comment]
@Harry-1976 can you give me an example?

**Comment by Harry-1976** [comment]
Yes, that’s all. 
You can adjust the width or the aspect ratio of the button when needed.
