### ISSUE TITLE
Custom header deprecated as of 0.116

### ISSUE THREAD

**Issue by philhawthorne** [N-l1/lovelace-soft-ui#34]
The readme has a section on the custom header component.

Unfortunately this project is no longer maintained and may cause issues in Home Assistant versions 0.117+

**Comment by KTibow** [comment]
Well let's just wait for 0.117. Should I link the card-mod wiki there instead?

**Comment by N-l1** [comment]
Thanks Phil! For now, it's removed from the readme.
