### ISSUE TITLE
Alignment broken in 0.117

### ISSUE THREAD

**Issue by philhawthorne** [N-l1/lovelace-soft-ui#35]
There are changes in 0.117 which makes the alignment of the secondary text in vertical buttons broken.

![image](https://user-images.githubusercontent.com/716711/97064594-c36e8080-15f2-11eb-9ed1-a6cad755f37a.png)

**Comment by KTibow** [comment]
Card-mod markdown broke again? Try asking on the forum of card-mod.

**Comment by philhawthorne** [comment]
> Card-mod markdown broke again?

No. Soft UI does some pretty neat tricks with CSS, which will need to be updated when the next release comes out, like we've had to do in the past

**Comment by KTibow** [comment]
It uses CSS in order to style it with card-mod. That's why I recommend asking over there.

**Comment by ASNNetworks** [comment]
It’s due to markdown card styling in HA 117. See my ticket: https://github.com/home-assistant/frontend/issues/7578

I asked around on the forum without luck, so decided to create a ticket in hopes of a more permanent solution.

**Comment by philhawthorne** [comment]
Thanks @ASNNetworks 

I've subscribed to that issue as well, let's see what comes out

**Comment by K-RAD** [comment]
Someone suggested using this:

content: |
  # Big text
  ## Small text
style:
  .: |
    ha-card {
      --ha-card-background: none !important;
      box-shadow: none !important;
      margin-top: 15px;
    }
  ha-markdown:
    $: |
      ha-markdown-element {
        letter-spacing: 0;
      }
      h1 {
        font-size: 20px !important;
        margin-bottom:5px;
      }
      h2 {
        font-size: 15px !important;
        margin-top:0;
        opacity: 1;
      }
type: markdown

**Comment by N-l1** [comment]
Thanks @K-RAD, works great! I've updated the card configs 422d5cf
