### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by supertabouret** [N-l1/lovelace-soft-ui#36]
Hi is very sexy indeed. For now i started from scratch with one button only and it s very slow..

views:
  - title: Maison
    path: maison
    badges: []
    cards: null
    entity: light.lumiere_pierre
    icon: 'mdi:lamp'
    show_icon: true
    show_name: false
    styles:
      card:
        - width: 60px
        - height: 60px
        - margin: 10px
        - border-radius: 15px
        - box-shadow: >
            [[[ return states['sun.sun'].state == 'below_horizon'

            ? '-5px -5px 8px rgba(50, 50, 50, .2), 5px 5px 8px rgba(0, 0, 0,
            .08)'

            : '-4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0,
            .03)';

            ]]]
        - background-color: var(--primary-background-color)
      icon:
        - color: var(--primary-text-color)
    state:
      - value: 'on'
        styles:
          card:
            - box-shadow: >
                [[[ return states['sun.sun'].state == 'below_horizon'

                ? 'inset -3px -3px 5px rgba(50, 50, 50, .5), inset 3px 3px 5px
                rgba(0, 0, 0, .3)'

                : 'inset -3px -3px 5px rgba(255, 255, 255, .65), inset 3px 3px
                5px rgba(0, 0, 0, .035)';

                ]]]
          icon:
            - color: var(--paper-item-icon-active-color)
    tap_action:
      action: toggle
      haptic: light
    hold_action:
      action: more-info
      haptic: medium
    type: 'custom:button-card'

**Comment by N-l1** [comment]
Hi @supertabouret, what version of HA are you using? Try updating to the latest release, clearing everything that's unnecessary in Lovelace and restart & refresh. I and, I presume a few others, have not had this problem, hence it is most likely not because of the code. Thanks
