### ISSUE TITLE
Request to fix GitHub Pages

### ISSUE THREAD

**Issue by KTibow** [N-l1/lovelace-soft-ui#6]
**Describe the problem**
Basically, when you go to [n-l1.github.io/lovelace-soft-ui](https://n-l1.github.io/lovelace-soft-ui/), right now you get a blank page.

**To Fix**
Steps to fix the behavior:
1. Go to [`docs`](https://github.com/N-l1/lovelace-soft-ui/tree/master/docs)
2. Click on `index.html`
3. Click on the trash can
4. Confirm the commit
5. Go to the [`Settings`](https://github.com/N-l1/lovelace-soft-ui/settings)
6. Scroll down to `GitHub Pages`
7. Click on the `Source` dropdown
8. Choose `master branch`
9. You're done! Now consider setting the URL of this repo to `https://n-l1.github.io/lovelace-soft-ui/`. There's an edit button next to the description on the main page.

**Comment by N-l1** [comment]
Yes, I never got around to do anything GitHub pages. It has now been temporarily disabled.

**Comment by KTibow** [comment]
@N-l1, by the way, GitHub Pages can automatically convert your `README.md` into a webpage, so you don't need to do any manual work. No pressure.

**Comment by N-l1** [comment]
Yes, I am aware of that
